# version: "3.8"
services:
  book-service-db:
    image: mongo:latest
    container_name: book-service-db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  book-service:
    build: ./book-service
    image: book-service:latest
    container_name: book-service
    ports:
      - 3000:3000
    networks:
      - app-network
    environment:
      - DATABASE_URL=mongodb://book-service-db:27017/books
    depends_on:
      - book-service-db

  loan-service:
    build: ./loan-service
    image: loan-service:latest
    container_name: loan-service
    ports:
      - 3001:3001
    networks:
      - app-network
    environment:
      - BOOK_SERVICE_URL=http://book-service:3000/books

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - book-service
      - loan-service

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
